# Generated by Django 3.2.13 on 2022-07-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_soiltestreports_test_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestreports',
            name='test_reports',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
