# Generated by Django 3.2.13 on 2022-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyoyeedailytask',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
