# Generated by Django 3.2.13 on 2022-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_emplyoyeedailytask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyoyeedailytask',
            name='date',
            field=models.DateField(),
        ),
    ]
