# Generated by Django 3.2.13 on 2022-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_emplyoyeedailytask_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(choices=[('Urea', 'Urea'), ('Phosphorus', 'Phosphorus'), ('Potassium', 'Potassium'), ('Rock Phospate', 'Rock Phospate'), ('Nitrogen', 'Nitrogen')], max_length=25, unique=True)),
                ('stock_units', models.PositiveIntegerField()),
            ],
        ),
    ]
