# Generated by Django 3.2.13 on 2022-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_fertilizerstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(choices=[('Ground Nuts', 'Ground Nuts'), ('Sun Flower', 'Sun Flower'), ('Paddy', 'paddy'), ('Wheat', 'Wheat'), ('Rice', 'Rice')], max_length=25, unique=True)),
                ('stock_units', models.PositiveIntegerField()),
            ],
        ),
    ]
