# Generated by Django 3.2.13 on 2022-07-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_seedstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamersFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=100)),
                ('feedback_desc', models.TextField()),
            ],
        ),
    ]
