# Generated by Django 3.2.13 on 2022-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_famersfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='famersfeedback',
            name='farmer_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famersfeedback',
            name='farmer_user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
