# Generated by Django 3.2.13 on 2022-07-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_soiltestreports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoilTestReports',
        ),
    ]
