# Generated by Django 3.2.13 on 2022-07-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTestSlotBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('login_id', models.CharField(max_length=120, unique=True)),
                ('father_name', models.CharField(max_length=120)),
                ('survey_no', models.CharField(max_length=120)),
                ('mobile_no', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('soil_type', models.CharField(choices=[('Red soil', 'Red soil'), ('Black soil ', 'Black soil'), ('Deltaic alluvial soil', 'Deltaic alluvial soil'), ('Coastal alluvial soil', 'Coastal alluvial soil'), ('Laterite soil', 'Laterite soil'), ('Skeletal Soil', 'Skeletal Soil')], max_length=25)),
            ],
            options={
                'db_table': 'SoilTestSlotBooking',
            },
        ),
    ]
