# Generated by Django 3.2.13 on 2022-07-06 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_soiltestslotbookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltestslotbookingmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soiltestslotbookingmodel',
            name='tracking_id',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='login_id',
            field=models.CharField(max_length=120),
        ),
    ]
