# Generated by Django 3.2.13 on 2022-07-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_auto_20220706_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='tracking_id',
            field=models.CharField(default=5505872240, max_length=10, unique=True),
        ),
    ]
