# Generated by Django 3.2.13 on 2022-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_soiltestslotbookingmodel_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='tracking_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
