# Generated by Django 3.2.13 on 2022-07-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_soiltestslotbookingmodel_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltestslotbookingmodel',
            name='status',
            field=models.CharField(default='placed', max_length=120),
        ),
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='tracking_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
