# Generated by Django 3.2.13 on 2022-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0007_alter_soiltestslotbookingmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('processed', 'processed'), ('accepted', 'accepted'), ('slotAlloted', 'slotAlloted'), ('result', 'result')], default='placed', max_length=120),
        ),
    ]
