# Generated by Django 3.2.13 on 2022-07-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_auto_20220706_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerregistrationmodel',
            old_name='login_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='soiltestslotbookingmodel',
            old_name='login_id',
            new_name='user_id',
        ),
    ]
