# Generated by Django 3.2.13 on 2022-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_seedtestslotbookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizersOrderingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('user_id', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('survey_no', models.CharField(max_length=120)),
                ('mobile_no', models.CharField(max_length=120)),
                ('no_of_packets', models.PositiveIntegerField()),
                ('fertilizer_type', models.CharField(choices=[('Urea', 'Urea'), ('Phosphorus', 'Phosphorus'), ('Potassium', 'Potassium'), ('Rock Phospate', 'Rock Phospate'), ('Nitrogen', 'Nitrogen')], max_length=25)),
                ('address', models.CharField(max_length=120)),
                ('tracking_id', models.CharField(max_length=16, unique=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('placed', 'placed'), ('processed', 'processed'), ('accepted', 'accepted'), ('slotAlloted', 'slotAlloted'), ('result', 'result')], default='placed', max_length=120)),
            ],
            options={
                'db_table': 'FertilizersOrdering',
            },
        ),
    ]
