# Generated by Django 3.2.13 on 2022-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_fertilizersorderingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedsOrderingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('user_id', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('survey_no', models.CharField(max_length=120)),
                ('mobile_no', models.CharField(max_length=120)),
                ('seed_type', models.CharField(choices=[('Ground Nuts', 'Ground Nuts'), ('Sun Flower', 'Sun Flower'), ('Paddy', 'paddy'), ('Wheat', 'Wheat'), ('Rice', 'Rice')], max_length=25)),
                ('no_of_packets', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=120)),
                ('tracking_id', models.CharField(max_length=16, unique=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('placed', 'placed'), ('processed', 'processed'), ('accepted', 'accepted'), ('slotAlloted', 'slotAlloted'), ('result', 'result')], default='placed', max_length=120)),
            ],
            options={
                'db_table': 'SeedsOrdering',
            },
        ),
        migrations.DeleteModel(
            name='SeedTestSlotBookingModel',
        ),
    ]
