# Generated by Django 3.2.13 on 2022-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_auto_20220716_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsorderingmodel',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('processed', 'processed'), ('pickedUp', 'pickedUp'), ('shipped', 'shipped'), ('outOfDelivery', 'outOfDelivery'), ('delivered', 'delivered')], default='placed', max_length=120),
        ),
    ]
