# Generated by Django 3.2.13 on 2022-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_alter_seedsorderingmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltestslotbookingmodel',
            name='soil_type',
            field=models.CharField(choices=[('Red-soil', 'Red soil'), ('Black-soil', 'Black soil'), ('Deltaic-alluvial-soil', 'Deltaic alluvial soil'), ('Coastal-alluvial-soil', 'Coastal alluvial soil'), ('Laterite-soil', 'Laterite soil'), ('Skeletal-Soil', 'Skeletal Soil')], max_length=25),
        ),
    ]
