# Generated by Django 3.2.13 on 2022-07-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0014_alter_soiltestslotbookingmodel_soil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizersorderingmodel',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('processed', 'processed'), ('pickedUp', 'pickedUp'), ('shipped', 'shipped'), ('outOfDelivery', 'outOfDelivery'), ('delivered', 'delivered')], default='placed', max_length=120),
        ),
    ]
